name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [core, cache, test]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
      - name: Format check
        run: dart format --output=none --set-exit-if-changed .
        working-directory: packages/${{ matrix.package }}
      - name: Analyze
        run: dart analyze
        working-directory: packages/${{ matrix.package }}
      - name: Test
        run: dart test
        working-directory: packages/${{ matrix.package }}
      - name: Dry-run publish
        run: dart pub publish --dry-run
        working-directory: packages/${{ matrix.package }}
